code = """
FILE SALES
  SALES-ID     1  10  A
  SALES-AMT    11 6  N

JOB INPUT SALES
  PRINT REPORT
  RUN

REPORT REPORT
  LINE 01 COL 01 'SALES REPORT'
  LINE 02 COL 01 '============='
  LINE 03 COL 01 'SALES-ID' COL 15 'SALES-AMT'
  LINE 04 COL 01 SALES-ID COL 15 SALES-AMT

"""