EntityMetadata {
  '@instanceof': Symbol(EntityMetadata),
  childEntityMetadatas: [],
  inheritanceTree: [ [class CustomerEntity] ],
  tableType: 'regular',
  withoutRowid: false,
  synchronize: true,
  hasNonNullableRelations: false,
  isJunction: false,
  isAlwaysUsingConstructor: true,
  isClosureJunction: false,
  hasMultiplePrimaryKeys: false,
  hasUUIDGeneratedColumns: false,
  ownColumns: [
    ColumnMetadata {
      '@instanceof': Symbol(ColumnMetadata),
      length: '',
      isPrimary: true,
      isGenerated: false,
      isNullable: false,
      isSelect: true,
      isInsert: true,
      isUpdate: true,
      zerofill: false,
      unsigned: false,
      isArray: false,
      isVirtual: false,
      isDiscriminator: false,
      isTreeLevel: false,
      isCreateDate: false,
      isUpdateDate: false,
      isDeleteDate: false,
      isVersion: false,
      isObjectId: false,
      isNestedSetLeft: false,
      isNestedSetRight: false,
      isMaterializedPath: false,
      entityMetadata: [Circular *1],
      embeddedMetadata: undefined,
      referencedColumn: undefined,
      target: [class CustomerEntity],
      propertyName: 'id',
      type: [Function: String],
      precision: undefined,
      propertyPath: 'id',
      propertyAliasName: 'id',
      databaseName: 'id',
      databasePath: 'id',
      databaseNameWithoutPrefixes: 'id'
    },
    ColumnMetadata {
      '@instanceof': Symbol(ColumnMetadata),
      length: '',
      isPrimary: false,
      isGenerated: false,
      isNullable: true,
      isSelect: true,
      isInsert: true,
      isUpdate: true,
      zerofill: false,
      unsigned: false,
      isArray: false,
      isVirtual: false,
      isDiscriminator: false,
      isTreeLevel: false,
      isCreateDate: false,
      isUpdateDate: false,
      isDeleteDate: false,
      isVersion: false,
      isObjectId: false,
      isNestedSetLeft: false,
      isNestedSetRight: false,
      isMaterializedPath: false,
      entityMetadata: [Circular *1],
      embeddedMetadata: undefined,
      referencedColumn: undefined,
      target: [class CustomerEntity],
      propertyName: 'referenceId',
      type: [Function: String],
      precision: undefined,
      propertyPath: 'referenceId',
      propertyAliasName: 'referenceId',
      databaseName: 'referenceId',
      databasePath: 'referenceId',
      databaseNameWithoutPrefixes: 'referenceId'
    },
    ColumnMetadata {
      '@instanceof': Symbol(ColumnMetadata),
      length: '',
      isPrimary: false,
      isGenerated: false,
      isNullable: false,
      isSelect: true,
      isInsert: true,
      isUpdate: true,
      zerofill: false,
      unsigned: false,
      isArray: false,
      isVirtual: false,
      isDiscriminator: false,
      isTreeLevel: false,
      isCreateDate: false,
      isUpdateDate: false,
      isDeleteDate: false,
      isVersion: false,
      isObjectId: false,
      isNestedSetLeft: false,
      isNestedSetRight: false,
      isMaterializedPath: false,
      entityMetadata: [Circular *1],
      embeddedMetadata: undefined,
      referencedColumn: undefined,
      target: [class CustomerEntity],
      propertyName: 'name',
      type: [Function: String],
      precision: undefined,
      propertyPath: 'name',
      propertyAliasName: 'name',
      databaseName: 'name',
      databasePath: 'name',
      databaseNameWithoutPrefixes: 'name'
    },
    ColumnMetadata {
      '@instanceof': Symbol(ColumnMetadata),
      length: '',
      isPrimary: false,
      isGenerated: false,
      isNullable: false,
      isSelect: true,
      isInsert: true,
      isUpdate: true,
      zerofill: false,
      unsigned: false,
      isArray: false,
      isVirtual: false,
      isDiscriminator: false,
      isTreeLevel: false,
      isCreateDate: false,
      isUpdateDate: false,
      isDeleteDate: false,
      isVersion: false,
      isObjectId: false,
      isNestedSetLeft: false,
      isNestedSetRight: false,
      isMaterializedPath: false,
      entityMetadata: [Circular *1],
      embeddedMetadata: undefined,
      referencedColumn: undefined,
      target: [class CustomerEntity],
      propertyName: 'email',
      type: [Function: String],
      precision: undefined,
      propertyPath: 'email',
      propertyAliasName: 'email',
      databaseName: 'email',
      databasePath: 'email',
      databaseNameWithoutPrefixes: 'email'
    },
    ColumnMetadata {
      '@instanceof': Symbol(ColumnMetadata),
      length: '',
      isPrimary: false,
      isGenerated: false,
      isNullable: true,
      isSelect: true,
      isInsert: true,
      isUpdate: true,
      zerofill: false,
      unsigned: false,
      isArray: false,
      isVirtual: false,
      isDiscriminator: false,
      isTreeLevel: false,
      isCreateDate: false,
      isUpdateDate: false,
      isDeleteDate: false,
      isVersion: false,
      isObjectId: false,
      isNestedSetLeft: false,
      isNestedSetRight: false,
      isMaterializedPath: false,
      entityMetadata: [Circular *1],
      embeddedMetadata: undefined,
      referencedColumn: undefined,
      target: [class CustomerEntity],
      propertyName: 'phone',
      type: [Function: String],
      precision: undefined,
      propertyPath: 'phone',
      propertyAliasName: 'phone',
      databaseName: 'phone',
      databasePath: 'phone',
      databaseNameWithoutPrefixes: 'phone'
    }
  ],
  columns: [
    ColumnMetadata {
      '@instanceof': Symbol(ColumnMetadata),
      length: '',
      isPrimary: true,
      isGenerated: false,
      isNullable: false,
      isSelect: true,
      isInsert: true,
      isUpdate: true,
      zerofill: false,
      unsigned: false,
      isArray: false,
      isVirtual: false,
      isDiscriminator: false,
      isTreeLevel: false,
      isCreateDate: false,
      isUpdateDate: false,
      isDeleteDate: false,
      isVersion: false,
      isObjectId: false,
      isNestedSetLeft: false,
      isNestedSetRight: false,
      isMaterializedPath: false,
      entityMetadata: [Circular *1],
      embeddedMetadata: undefined,
      referencedColumn: undefined,
      target: [class CustomerEntity],
      propertyName: 'id',
      type: [Function: String],
      precision: undefined,
      propertyPath: 'id',
      propertyAliasName: 'id',
      databaseName: 'id',
      databasePath: 'id',
      databaseNameWithoutPrefixes: 'id'
    },
    ColumnMetadata {
      '@instanceof': Symbol(ColumnMetadata),
      length: '',
      isPrimary: false,
      isGenerated: false,
      isNullable: true,
      isSelect: true,
      isInsert: true,
      isUpdate: true,
      zerofill: false,
      unsigned: false,
      isArray: false,
      isVirtual: false,
      isDiscriminator: false,
      isTreeLevel: false,
      isCreateDate: false,
      isUpdateDate: false,
      isDeleteDate: false,
      isVersion: false,
      isObjectId: false,
      isNestedSetLeft: false,
      isNestedSetRight: false,
      isMaterializedPath: false,
      entityMetadata: [Circular *1],
      embeddedMetadata: undefined,
      referencedColumn: undefined,
      target: [class CustomerEntity],
      propertyName: 'referenceId',
      type: [Function: String],
      precision: undefined,
      propertyPath: 'referenceId',
      propertyAliasName: 'referenceId',
      databaseName: 'referenceId',
      databasePath: 'referenceId',
      databaseNameWithoutPrefixes: 'referenceId'
    },
    ColumnMetadata {
      '@instanceof': Symbol(ColumnMetadata),
      length: '',
      isPrimary: false,
      isGenerated: false,
      isNullable: false,
      isSelect: true,
      isInsert: true,
      isUpdate: true,
      zerofill: false,
      unsigned: false,
      isArray: false,
      isVirtual: false,
      isDiscriminator: false,
      isTreeLevel: false,
      isCreateDate: false,
      isUpdateDate: false,
      isDeleteDate: false,
      isVersion: false,
      isObjectId: false,
      isNestedSetLeft: false,
      isNestedSetRight: false,
      isMaterializedPath: false,
      entityMetadata: [Circular *1],
      embeddedMetadata: undefined,
      referencedColumn: undefined,
      target: [class CustomerEntity],
      propertyName: 'name',
      type: [Function: String],
      precision: undefined,
      propertyPath: 'name',
      propertyAliasName: 'name',
      databaseName: 'name',
      databasePath: 'name',
      databaseNameWithoutPrefixes: 'name'
    },
    ColumnMetadata {
      '@instanceof': Symbol(ColumnMetadata),
      length: '',
      isPrimary: false,
      isGenerated: false,
      isNullable: false,
      isSelect: true,
      isInsert: true,
      isUpdate: true,
      zerofill: false,
      unsigned: false,
      isArray: false,
      isVirtual: false,
      isDiscriminator: false,
      isTreeLevel: false,
      isCreateDate: false,
      isUpdateDate: false,
      isDeleteDate: false,
      isVersion: false,
      isObjectId: false,
      isNestedSetLeft: false,
      isNestedSetRight: false,
      isMaterializedPath: false,
      entityMetadata: [Circular *1],
      embeddedMetadata: undefined,
      referencedColumn: undefined,
      target: [class CustomerEntity],
      propertyName: 'email',
      type: [Function: String],
      precision: undefined,
      propertyPath: 'email',
      propertyAliasName: 'email',
      databaseName: 'email',
      databasePath: 'email',
      databaseNameWithoutPrefixes: 'email'
    },
    ColumnMetadata {
      '@instanceof': Symbol(ColumnMetadata),
      length: '',
      isPrimary: false,
      isGenerated: false,
      isNullable: true,
      isSelect: true,
      isInsert: true,
      isUpdate: true,
      zerofill: false,
      unsigned: false,
      isArray: false,
      isVirtual: false,
      isDiscriminator: false,
      isTreeLevel: false,
      isCreateDate: false,
      isUpdateDate: false,
      isDeleteDate: false,
      isVersion: false,
      isObjectId: false,
      isNestedSetLeft: false,
      isNestedSetRight: false,
      isMaterializedPath: false,
      entityMetadata: [Circular *1],
      embeddedMetadata: undefined,
      referencedColumn: undefined,
      target: [class CustomerEntity],
      propertyName: 'phone',
      type: [Function: String],
      precision: undefined,
      propertyPath: 'phone',
      propertyAliasName: 'phone',
      databaseName: 'phone',
      databasePath: 'phone',
      databaseNameWithoutPrefixes: 'phone'
    }
  ],
  ancestorColumns: [],
  descendantColumns: [],
  nonVirtualColumns: [
    ColumnMetadata {
      '@instanceof': Symbol(ColumnMetadata),
      length: '',
      isPrimary: true,
      isGenerated: false,
      isNullable: false,
      isSelect: true,
      isInsert: true,
      isUpdate: true,
      zerofill: false,
      unsigned: false,
      isArray: false,
      isVirtual: false,
      isDiscriminator: false,
      isTreeLevel: false,
      isCreateDate: false,
      isUpdateDate: false,
      isDeleteDate: false,
      isVersion: false,
      isObjectId: false,
      isNestedSetLeft: false,
      isNestedSetRight: false,
      isMaterializedPath: false,
      entityMetadata: [Circular *1],
      embeddedMetadata: undefined,
      referencedColumn: undefined,
      target: [class CustomerEntity],
      propertyName: 'id',
      type: [Function: String],
      precision: undefined,
      propertyPath: 'id',
      propertyAliasName: 'id',
      databaseName: 'id',
      databasePath: 'id',
      databaseNameWithoutPrefixes: 'id'
    },
    ColumnMetadata {
      '@instanceof': Symbol(ColumnMetadata),
      length: '',
      isPrimary: false,
      isGenerated: false,
      isNullable: true,
      isSelect: true,
      isInsert: true,
      isUpdate: true,
      zerofill: false,
      unsigned: false,
      isArray: false,
      isVirtual: false,
      isDiscriminator: false,
      isTreeLevel: false,
      isCreateDate: false,
      isUpdateDate: false,
      isDeleteDate: false,
      isVersion: false,
      isObjectId: false,
      isNestedSetLeft: false,
      isNestedSetRight: false,
      isMaterializedPath: false,
      entityMetadata: [Circular *1],
      embeddedMetadata: undefined,
      referencedColumn: undefined,
      target: [class CustomerEntity],
      propertyName: 'referenceId',
      type: [Function: String],
      precision: undefined,
      propertyPath: 'referenceId',
      propertyAliasName: 'referenceId',
      databaseName: 'referenceId',
      databasePath: 'referenceId',
      databaseNameWithoutPrefixes: 'referenceId'
    },
    ColumnMetadata {
      '@instanceof': Symbol(ColumnMetadata),
      length: '',
      isPrimary: false,
      isGenerated: false,
      isNullable: false,
      isSelect: true,
      isInsert: true,
      isUpdate: true,
      zerofill: false,
      unsigned: false,
      isArray: false,
      isVirtual: false,
      isDiscriminator: false,
      isTreeLevel: false,
      isCreateDate: false,
      isUpdateDate: false,
      isDeleteDate: false,
      isVersion: false,
      isObjectId: false,
      isNestedSetLeft: false,
      isNestedSetRight: false,
      isMaterializedPath: false,
      entityMetadata: [Circular *1],
      embeddedMetadata: undefined,
      referencedColumn: undefined,
      target: [class CustomerEntity],
      propertyName: 'name',
      type: [Function: String],
      precision: undefined,
      propertyPath: 'name',
      propertyAliasName: 'name',
      databaseName: 'name',
      databasePath: 'name',
      databaseNameWithoutPrefixes: 'name'
    },
    ColumnMetadata {
      '@instanceof': Symbol(ColumnMetadata),
      length: '',
      isPrimary: false,
      isGenerated: false,
      isNullable: false,
      isSelect: true,
      isInsert: true,
      isUpdate: true,
      zerofill: false,
      unsigned: false,
      isArray: false,
      isVirtual: false,
      isDiscriminator: false,
      isTreeLevel: false,
      isCreateDate: false,
      isUpdateDate: false,
      isDeleteDate: false,
      isVersion: false,
      isObjectId: false,
      isNestedSetLeft: false,
      isNestedSetRight: false,
      isMaterializedPath: false,
      entityMetadata: [Circular *1],
      embeddedMetadata: undefined,
      referencedColumn: undefined,
      target: [class CustomerEntity],
      propertyName: 'email',
      type: [Function: String],
      precision: undefined,
      propertyPath: 'email',
      propertyAliasName: 'email',
      databaseName: 'email',
      databasePath: 'email',
      databaseNameWithoutPrefixes: 'email'
    },
    ColumnMetadata {
      '@instanceof': Symbol(ColumnMetadata),
      length: '',
      isPrimary: false,
      isGenerated: false,
      isNullable: true,
      isSelect: true,
      isInsert: true,
      isUpdate: true,
      zerofill: false,
      unsigned: false,
      isArray: false,
      isVirtual: false,
      isDiscriminator: false,
      isTreeLevel: false,
      isCreateDate: false,
      isUpdateDate: false,
      isDeleteDate: false,
      isVersion: false,
      isObjectId: false,
      isNestedSetLeft: false,
      isNestedSetRight: false,
      isMaterializedPath: false,
      entityMetadata: [Circular *1],
      embeddedMetadata: undefined,
      referencedColumn: undefined,
      target: [class CustomerEntity],
      propertyName: 'phone',
      type: [Function: String],
      precision: undefined,
      propertyPath: 'phone',
      propertyAliasName: 'phone',
      databaseName: 'phone',
      databasePath: 'phone',
      databaseNameWithoutPrefixes: 'phone'
    }
  ],
  ownerColumns: [],
  inverseColumns: [],
  generatedColumns: [],
  primaryColumns: [
    ColumnMetadata {
      '@instanceof': Symbol(ColumnMetadata),
      length: '',
      isPrimary: true,
      isGenerated: false,
      isNullable: false,
      isSelect: true,
      isInsert: true,
      isUpdate: true,
      zerofill: false,
      unsigned: false,
      isArray: false,
      isVirtual: false,
      isDiscriminator: false,
      isTreeLevel: false,
      isCreateDate: false,
      isUpdateDate: false,
      isDeleteDate: false,
      isVersion: false,
      isObjectId: false,
      isNestedSetLeft: false,
      isNestedSetRight: false,
      isMaterializedPath: false,
      entityMetadata: [Circular *1],
      embeddedMetadata: undefined,
      referencedColumn: undefined,
      target: [class CustomerEntity],
      propertyName: 'id',
      type: [Function: String],
      precision: undefined,
      propertyPath: 'id',
      propertyAliasName: 'id',
      databaseName: 'id',
      databasePath: 'id',
      databaseNameWithoutPrefixes: 'id'
    }
  ],
  ownRelations: [],
  relations: [],
  eagerRelations: [],
  lazyRelations: [],
  oneToOneRelations: [],
  ownerOneToOneRelations: [],
  oneToManyRelations: [],
  manyToOneRelations: [],
  manyToManyRelations: [],
  ownerManyToManyRelations: [],
  relationsWithJoinColumns: [],
  relationIds: [],
  relationCounts: [],
  foreignKeys: [],
  embeddeds: [],
  allEmbeddeds: [],
  ownIndices: [
    IndexMetadata {
      isUnique: true,
      isSpatial: false,
      isFulltext: false,
      isNullFiltered: false,
      synchronize: true,
      columns: [Array],
      columnNamesWithOrderingMap: [Object],
      entityMetadata: [Circular *1],
      embeddedMetadata: undefined,
      target: [class CustomerEntity],
      parser: undefined,
      where: undefined,
      isSparse: undefined,
      isBackground: undefined,
      expireAfterSeconds: undefined,
      givenName: undefined,
      givenColumnNames: [Array],
      name: 'IDX_04b29aa9275dcb75035049b743'
    }
  ],
  indices: [
    IndexMetadata {
      isUnique: true,
      isSpatial: false,
      isFulltext: false,
      isNullFiltered: false,
      synchronize: true,
      columns: [Array],
      columnNamesWithOrderingMap: [Object],
      entityMetadata: [Circular *1],
      embeddedMetadata: undefined,
      target: [class CustomerEntity],
      parser: undefined,
      where: undefined,
      isSparse: undefined,
      isBackground: undefined,
      expireAfterSeconds: undefined,
      givenName: undefined,
      givenColumnNames: [Array],
      name: 'IDX_04b29aa9275dcb75035049b743'
    }
  ],
  uniques: [],
  ownUniques: [],
  checks: [],
  exclusions: [],
  ownListeners: [
    EntityListenerMetadata {
      entityMetadata: [Circular *1],
      embeddedMetadata: undefined,
      target: [class CustomerEntity],
      propertyName: '_setPrimary',
      type: 'before-insert'
    }
  ],
  listeners: [
    EntityListenerMetadata {
      entityMetadata: [Circular *1],
      embeddedMetadata: undefined,
      target: [class CustomerEntity],
      propertyName: '_setPrimary',
      type: 'before-insert'
    }
  ],
  afterLoadListeners: [],
  beforeInsertListeners: [
    EntityListenerMetadata {
      entityMetadata: [Circular *1],
      embeddedMetadata: undefined,
      target: [class CustomerEntity],
      propertyName: '_setPrimary',
      type: 'before-insert'
    }
  ],
  afterInsertListeners: [],
  beforeUpdateListeners: [],
  afterUpdateListeners: [],
  beforeRemoveListeners: [],
  beforeSoftRemoveListeners: [],
  beforeRecoverListeners: [],
  afterRemoveListeners: [],
  afterSoftRemoveListeners: [],
  afterRecoverListeners: [],
  connection: <ref *2> DataSource {
    '@instanceof': Symbol(DataSource),
    migrations: [],
    subscribers: [],
    entityMetadatas: [
      [EntityMetadata], [EntityMetadata],
      [EntityMetadata], [EntityMetadata],
      [EntityMetadata], [Circular *1],
      [EntityMetadata], [EntityMetadata],
      [EntityMetadata], [EntityMetadata],
      [EntityMetadata], [EntityMetadata],
      [EntityMetadata], [EntityMetadata],
      [EntityMetadata], [EntityMetadata],
      [EntityMetadata], [EntityMetadata],
      [EntityMetadata], [EntityMetadata]
    ],
    name: 'homegauge',
    options: {
      name: 'homegauge',
      type: 'mysql',
      port: 3306,
      host: '127.0.0.1',
      username: 'root',
      password: 'password',
      database: 'homegauge',
      autoLoadEntities: true,
      entities: [Array],
      synchronize: false,
      logging: [Array]
    },
    logger: AdvancedConsoleLogger { options: [Array] },
    driver: MysqlDriver {
      isReplicated: false,
      treeSupport: true,
      transactionSupport: 'nested',
      supportedDataTypes: [Array],
      supportedUpsertType: 'on-duplicate-key-update',
      spatialTypes: [Array],
      withLengthColumnTypes: [Array],
      withWidthColumnTypes: [Array],
      withPrecisionColumnTypes: [Array],
      withScaleColumnTypes: [Array],
      unsignedAndZerofillTypes: [Array],
      mappedDataTypes: [Object],
      dataTypeDefaults: [Object],
      maxAliasLength: 63,
      cteCapabilities: [Object],
      _isReturningSqlSupported: [Object],
      connection: [Circular *2],
      options: [Object],
      mysql: [Object],
      database: 'homegauge',
      pool: [Pool]
    },
    manager: EntityManager {
      '@instanceof': Symbol(EntityManager),
      repositories: [],
      treeRepositories: [],
      plainObjectToEntityTransformer: PlainObjectToNewEntityTransformer {},
      connection: [Circular *2]
    },
    namingStrategy: DefaultNamingStrategy {
      nestedSetColumnNames: [Object],
      materializedPathColumnName: 'mpath'
    },
    metadataTableName: 'typeorm_metadata',
    queryResultCache: undefined,
    relationLoader: RelationLoader { connection: [Circular *2] },
    relationIdLoader: RelationIdLoader { connection: [Circular *2] },
    isInitialized: true
  },
  inheritancePattern: undefined,
  treeType: undefined,
  treeOptions: undefined,
  parentClosureEntityMetadata: undefined,
  tableMetadataArgs: {
    target: [class CustomerEntity],
    name: 'customer',
    type: 'regular',
    orderBy: undefined,
    engine: undefined,
    database: undefined,
    schema: undefined,
    synchronize: undefined,
    withoutRowid: undefined
  },
  target: [class CustomerEntity],
  expression: undefined,
  dependsOn: undefined,
  engine: undefined,
  database: undefined,
  givenTableName: 'customer',
  targetName: 'CustomerEntity',
  tableNameWithoutPrefix: 'customer',
  tableName: 'customer',
  name: 'CustomerEntity',
  tablePath: 'customer',
  orderBy: undefined,
  discriminatorValue: 'CustomerEntity',
  treeParentRelation: undefined,
  treeChildrenRelation: undefined,
  createDateColumn: undefined,
  updateDateColumn: undefined,
  deleteDateColumn: undefined,
  versionColumn: undefined,
  discriminatorColumn: undefined,
  treeLevelColumn: undefined,
  nestedSetLeftColumn: undefined,
  nestedSetRightColumn: undefined,
  materializedPathColumn: undefined,
  objectIdColumn: undefined,
  propertiesMap: {
    id: 'id',
    referenceId: 'referenceId',
    name: 'name',
    email: 'email',
    phone: 'phone'
  }
}